giffy-django/giffy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("giffy_app.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

giffy-django/giffy_app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import IndexView, SignUpView, UploadImageView

app_name = "giffy_app"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "login/",
        LoginView.as_view(
            template_name="giffy_app/login.html",
            next_page="giffy_app:index",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(next_page="giffy_app:index"),
        name="logout",
    ),
    path("signup/", SignUpView.as_view(), name="signup"),
    # Added upload view here, don't forget to
    # import UploadImageView from .views
    path("upload/", UploadImageView.as_view(), name="upload"),
]

giffy-django/giffy_app/models.py
from django.conf import settings
from django.db import models


class Image(models.Model):
    # image title, not blank string with maximum of 60 characters
    title = models.CharField(max_length=60, blank=False)

    # the uploaded image. It is important to understand that
    # django will not store the image in the database.
    # The image field in the database table will contain the
    # image name (with max_length = 36) whereas the actual image
    # will be stored in the directory defined in giffy/settings.py.
    image = models.ImageField(max_length=36)

    # image upload date and time
    uploaded_date = models.DateTimeField()

    # link to the user that uploaded the image
    uploaded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self) -> str:
        return f"Image<{self.id}>"

giffy-django/giffy_app/forms.py
from django import forms

from .models import Image

# We use Django's built-in ModelForm class
class UploadImageForm(forms.ModelForm):
    class Meta:
        model = Image
        # only image and title fields from the Image
        # model will be available to user
        fields = ["image", "title"]
        # Let's play with it a little to
        # get a taste of Django widgets
        widgets = {
            "title": forms.Textarea(
                attrs={
                    "cols": 60,
                    "rows": 3,
                }
            ),
        }

giffy-django/giffy_app/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

# LoginRequiredMixin will check that user
# is authenticated before rendering the template.
from django.contrib.auth.mixins import LoginRequiredMixin

from datetime import datetime
from .models import Image
from .forms import UploadImageForm


class IndexView(View):
    def get(self, request):
        images = Image.objects.order_by("uploaded_date")
        return render(
            request,
            "giffy_app/index.html",
            {
                "images": images,
            },
        )


class SignUpView(View):
    def get(self, request):
        return render(
            request,
            "giffy_app/signup.html",
            {
                "form": UserCreationForm(),
            },
        )

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.data["username"]
            password = form.data["password1"]
            user = authenticate(
                request,
                username=username,
                password=password,
            )
            if user:
                login(request, user)
            return redirect("/")

        return render(
            request,
            "giffy_app/signup.html",
            {
                "form": form,
            },
        )


class UploadImageView(LoginRequiredMixin, View):
    # Not authenticated users will be redirected
    # to /login page if they try to access this view
    login_url = "/login/"

    def get(self, request):
        return render(
            request,
            "giffy_app/upload.html",
            {
                "form": UploadImageForm(),
            },
        )

    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            # Double check that user is authenticated
            raise Exception("User is not authenticated")

        # File, uploaded by user, will be available at request.FILES
        form = UploadImageForm(request.POST, request.FILES)

        if form.is_valid():
            # Creating a new image model instance
            img = Image(
                # get title from form.data
                title=form.data["title"],
                # get image from form.files
                image=form.files["image"],
                uploaded_date=datetime.now(),
                uploaded_by=user,
            )

            # save image to database
            img.save()

            # redirect to index page upon successful upload
            return redirect("/")

        # re-render form, show validation errors
        return render(
            request,
            "giffy_app/upload.html",
            {
                "form": form,
            },
        )

giffy-django/giffy_app/templates/giffy_app/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>Giffy</title>
  <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'giffy_app/styles.css' %}">
</head>

<body>
  <!-- Added header.html -->
  {% include 'giffy_app/header.html' %}

  {% block content %}
  {% endblock content %}
</body>

</html>

giffy-django/giffy_app/templates/giffy_app/header.html
<header>
  <nav>
    <a href="/">Home</a>

    <!-- added url 'giffy_app:upload' inside href attribute  -->
    <a href="{% url 'giffy_app:upload' %}" class="upload-btn">
      Upload
    </a>

    {% if user.is_authenticated %}
    <a href="{% url 'giffy_app:logout' %}">Logout</a>

    {% else %}

    <a href="{% url 'giffy_app:login' %}">Login</a>
    <a href="{% url 'giffy_app:signup' %}">Signup</a>

    {% endif %}
  </nav>
</header>

giffy-django/giffy_app/templates/giffy_app/image.html
<article class="centered">
  <!--
    Remember the { for image in images } from the index.html?
    image is basically the Image model from the giffy_app/models.py
  -->
  <h3>{{ image.title }}</h3>
  <!--
    Django generates image url for us. Since the image here is
    just an instance of the Image model from the giffy_app/models.py
    we can access the underlying file by calling image.image
  -->
  <img src="{{ image.image.url }}" />
  <p>Uploaded by {{ image.uploaded_by }}</p>
</article>

giffy-django/giffy_app/templates/giffy_app/index.html
{% extends "giffy_app/base.html" %}

{% block content %}
<main>
  {% for image in images %}
  {% include 'giffy_app/image.html' %}
  {% endfor%}
  <!--
  The construction above means the following:
  - for each image from the images list
  - go get giffy_app/image.html template, render it 
    and past the result here
-->
</main>
{% endblock content %}

giffy-django/giffy_app/templates/giffy_app/login.html
{% extends "giffy_app/base.html" %}

{% block content %}
<div class="centered">
  <h3>Login</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit" />
  </form>
</div>
{% endblock content %}

giffy-django/giffy_app/templates/giffy_app/signup.html
{% extends "giffy_app/base.html" %}

{% block content %}
<div class="centered">
  <h3>Sign up</h3>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form>
</div>
{% endblock content %}

giffy-django/giffy_app/templates/giffy_app/upload.html
{% extends "giffy_app/base.html" %}

{% block content %}
<div class="centered">
  <h3>Upload</h3>
  <!-- It's important to add enctype="multipart/form-data" -->
  <!-- param, otherwise django will fail to upload the image -->
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit" />
  </form>
</div>
{% endblock content %}